[package]
name = "sweepster"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal-fonts = "0.1.0"
csv = "1.1"
rust-code-analysis = "0.0.25"
